sudo: required
services:
  - docker

before_install:
  - docker build -t zamlythaha/docker-react -f Dockerfile.dev .

script:
  # - docker run zamlythaha/docker-react npm run test -- --coverage
  - docker run -e CI=true zamlythaha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-561421712725"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"