sudo: required
services:
  - docker

before_install:
  - docker build -t zamlythaha/docker-react -f Dockerfile.dev .

script:
  # - docker run zamlythaha/docker-react npm run test -- --coverage
  - docker run -e CI=true zamlythaha/docker-react npm run test